### ISSUE TITLE
ExtrinsicModel model initialziation issue

### ISSUE THREAD

**Issue by LevinJ** [DRosemei/RoMe#29]
In the scripts/train.py file,  we have ExtrinsicModel initialization line

```
poses = ExtrinsicModel(configs, optim_dict["rotations"], optim_dict["translations"], num_camera=len(dataset.camera_extrinsics)).to(device)
```

For the num_camera, I think we intend to set it as the number of cameras, but len(dataset.camera_extrinsics) is actually equal to the number of cameras multiply the number of key frames in the scene.

This issue can be re-produce by configuring only one camera like "CAM_FRONT", and then check the value of len(dataset.camera_extrinsics), we will see it's not equal to 1 as expected.

One possible way to fix this issue is to change the above line as below,

```
poses = ExtrinsicModel(configs, optim_dict["rotations"], optim_dict["translations"], num_camera=np.unique(dataset.cameras_idx_all).size).to(device)
```

**Comment by DRosemei** [comment]
@LevinJ As you can see, poses in nuscenes may not be correct, so if you only uses poses of "CAM_FRONT" and learn extrinsics, it may be limited to accuracy of poses of "CAM_FRONT". So we learn a slight rotation and translation on source poses to finetune poses.

**Comment by LevinJ** [comment]
Thanks for your kind reply. I am a bit confused.  From what I understand, source poses in nuscenes can be decomposed into two parts: 1, camera frame to vehicle frame transformation, 2, vehicle frame to world frame transformation.  We learn a slight rotation and translation on source poses by optimizing the first part. If we use only one camera,  then num_camera passed to ExtrinsicModel should be 1 too.  Is this true?  If num_camera is not expected to be 1 in this case, what would be its expected value?

**Comment by DRosemei** [comment]
We optimize delta poses from source poses derived from CAM_FRONT and extrinsics. 

1. We init pose by https://github.com/DRosemei/RoMe/blob/main/datasets/nusc.py#L93. So we get CAM_FRONT poses by extrinsics.
2. We then get poses from different cameras by https://github.com/DRosemei/RoMe/blob/main/datasets/nusc.py#L293.
3. Finally, we learn delta poses which could be considered as optimizing extrinsics.

In wild data, we do not use this part, because we have other traditional methods to learn good extrinsics like rig-ba in colmap or online calibration which are more accurate than this.
