### ISSUE TITLE
train, val and test scene split for nuscenes dataset

### ISSUE THREAD

**Issue by MinminYang33** [DRosemei/RoMe#43]
Hello,

I am new to this area. I was wondering how many scenes are used for training. Besides, it was mentioned in the paper that some certain scenes are selected for evaluation, but they are from the trainval split in the dataset. Any clarification would be appreciated.

**Comment by DRosemei** [comment]
@MinminYang33 RoMe is a reconstrution task, so for each scene we will apply RoMe to it and evaluate it on PSNR and mIoU.

**Comment by MinminYang33** [comment]
@DRosemei Thank you for your reply. As I delve deeper into the paper, more questions come up.

1. If I understand it correctly, you use the same scene for training and evaluation. Is it right?
2. According to the caption of figure 9 in your paper, you select 3 frames for evaluation and use the rest frames for training. How did you pick the 3 frames? Did you pick them randomly? 
3. Did you also pick 3 frames for evaluation for other experiments, such as the results reported in table I?
4. It seems that you use the point cloud to [estimate the flat plane](https://github.com/DRosemei/RoMe/blob/c1e4c4789c457e052d62fa9f4c27aafbcd02d7eb/datasets/nusc.py#L118), does the algorithm still work without using the point cloud data? I am asking this question because my own task is to reconstruct the mesh based on camera images only.
Thank you for your attention to these questions.

**Comment by DRosemei** [comment]
@MinminYang33 
1. Yes, we use the same scene for training and evaluation when we conduct experiments on multiple scenes.
2. For comparison with nerf, we uniformly sampled 3 frames for evaluation.
3. No, because it is a reconstruction task and we not only evalutate image quality, but also geometry.
4. It may not work well when road is not so flat. You can use sfm/MVS to get points for better reconstruction.

**Comment by MinminYang33** [comment]
Thank you for your reply. It helps a lot.
